#!/bin/bash 
# copyright by qianjun.gong
# 【建议采用环境变量的方式修改配置，而不建议修改脚本内容】

# 使用方式 ./push [dev/uat/prod]，如果当前分支有修改会自动存到stash暂存区
# 镜像tag规则：tag-环境-当前时间，如v1.5.0-dev-1908201001
# 缓存区保存名称规则：当前分支-当前分钟，如dev-latest-1908201005
# 前端发布需要添加服务器ssh-key，或者手动输入服务器密码
# 20191128: 前端编译时区分环境更新路由信息
# 20191210: 支持【hcfpack 分支名 [环境]】打包代码，不输入环境会识别分支名中的环境标识
# 20191220: 优化代码结构，支持rancher升级[mac安装依赖 brew install kubectl rancher-cli]，支持缓存
# 20191225: 现在不输入镜像名称，下次也不会提示你输入，工作负载名称输入错误，会提示重新输入
# 20191225: 支持使用用户环境变量覆盖脚本中的变量值
# 20191230: 现在通过项目环境变量文件来配置环境信息，脚本升级更方便，支持多项目。【推荐将脚本加入系统环境变量】
# 20200102: 1.现在环境变量不配置在脚本里，第一次启动会自动生成配置模板 2.脚本支持rancher自动升级，将skip_verify变量设置为true后，全程发布无需手动确认 3. 支持变量缓存

[ -f ../remote_publish.env ] && source ../remote_publish.env
# 脚本初始化
#========================================
version=v1.5.7
# 脚本缓存目录，可通过配置用户或系统环境变量的方式修改
project_env_dir=${project_env_dir:-~/.project}
# 脚本名称/路径
[ "$(basename "${0}")" != "${0}" ] && program_file_path="${0}" || program_file_path="$(which "${0}")"
program_file_name="$(basename "${0}")"
# 判断是否为git项目
! git status &> /dev/null && echo "version: $version" && exit 0
# 获取项目组名称，组与子组之间采用下划线分隔
git_remote_url=$(git remote -v | grep "(push)" | grep "^origin" | awk '{print $2}')
project_name=$(echo $git_remote_url | awk -F '/' '{print$NF}' | sed -e 's/.git//g')
project_group_name=$(echo $git_remote_url | grep -Eo '[:/]([^./]+/){1,}' | sed -e 's/^[:/]//' -e 's/\/$//')
# 初始化脚本缓存目录
[ ! -d "${project_env_dir}/${project_group_name/\//_}" ] && mkdir -p "${project_env_dir}/${project_group_name/\//_}"
# 缓存文件
cache_file=${project_env_dir}/${project_group_name/\//_}/${program_file_name}.cache
# 项目环境变量
project_env_file=${project_env_dir}/${project_group_name/\//_}/${program_file_name}.env
# 加载项目环境变量
[ -f "${project_env_file}" ] && source "${project_env_file}"
#========================================

[ "${version}" != "${created_version}" -a -f "${project_env_file}" ] && upgrading=true || upgrading=false

if [ ! -f "${project_env_file}" -o "${upgrading}" = "true" ]; then

	if [ "${upgrading}" = "true" ]; then
    read -p "环境变量文件版本与程序版本不一致，是否自动更新？[y/n]: " res
    [ "${res}" != "y" ] && exit 1
    echo "更新环境变量文件: ${project_env_file}"
    cp -rf "${project_env_file}" "${project_env_file}.tmp"
  else
    echo "生成环境变量文件: ${project_env_file}"
    echo "请手动修改文件，再继续..."
  fi
  
	cat > "${project_env_file}" << EOF
# 变量创建时，程序版本
created_version=${version}
# 此参数决定镜像版本的命名，镜像命名方式为 \${tag}-\${env}-\${date}，如 v1.5.0-dev-2020010110
tag=${tag:-v1.5.0}

# 后端打包基础镜像
base_image=${base_image}
# 后端打包命令额外参数
mvn_extra_param=${mvn_extra_param}
# 后端打包方式，dockerBuild-打包到本地镜像库，build-打包到远程镜像库
mvn_build_method=${mvn_build_method:-build}

# 定义环境分支名称
dev_branch=${dev_branch:-dev-latest}
uat_branch=${uat_branch:-release-latest}
prod_branch=${prod_branch:-master-latest}

# 定义镜像仓库地址，over_http表示镜像库是否是http协议的
dev_server=${dev_server}
dev_username=${dev_username}
dev_password=${dev_password}
dev_over_http=${dev_over_http}

uat_server=${uat_server}
uat_username=${uat_username}
uat_password=${uat_password}
uat_over_http=${uat_over_http}

prod_server=${prod_server}
prod_username=${prod_username}
prod_password=${prod_password}
prod_over_http=${prod_over_http}

# 仓库额外路径，如/docker，会拼接在镜像仓库地址后面
registry_extra_path=${registry_extra_path}

# 是否启用rancher自动部署
rancher_deploy=${rancher_deploy:-true}
# 定义rancher地址，用于rancher自动发布，注意命名空间是小写
dev_rancher_url=${dev_rancher_url}
dev_rancher_token=${dev_rancher_token}
dev_rancher_project_id=${dev_rancher_project_id}
dev_rancher_namespace=${dev_rancher_namespace:-default}

uat_rancher_url=${uat_rancher_url}
uat_rancher_token=${uat_rancher_token}
uat_rancher_project_id=${uat_rancher_project_id}
uat_rancher_namespace=${uat_rancher_namespace:-default}

prod_rancher_url=${prod_rancher_url}
prod_rancher_token=${prod_rancher_token}
prod_rancher_project_id=${prod_rancher_project_id}
prod_rancher_namespace=${prod_rancher_namespace:-default}

# 前端打包方式[server/local]，server在服务器上打包，local在本地打包
front_pack_method=${front_pack_method:-server}
# 远程打包信息，本地不安装docker环境的情况下，使用远程服务器的docker环境打包
# 注意在远程服务器上添加自己的ssh密钥
front_server_address=${front_server_address}
front_server_user=${front_server_user:-root}
front_server_dir=$(test -n "${front_server_dir}" && cat ${project_env_file} | grep front_server_dir | cut -d'=' -f2 | head -1 | sed -e 's/\$/\$/g' || echo -n "/home/web-front/\$(date +%y%m%d%H%M)")

# 前端项目名称，git仓库中的名称
front_module_name=${front_module_name:-front}
# 前端编译目标文件夹
front_local_dirname=${front_local_dirname:-dist}
# 自定义前端编译命令
front_build_cmd='${front_build_cmd}'
# 前端docker打包所需要的文件或文件夹，相对于项目根路径
front_docker_files='${front_docker_files:-./Dockerfile ./docker}'
# 本地打包目录，不建议设置为前端项目目录，设置为.时，会在项目根目录中打包
front_local_pack_dir='${front_local_pack_dir:-~/build}'

# 跳过确认步骤，跳过后执行程序全程无需确认，全自动发布
skip_verify=${skip_verify:-false}
# 推送latest标签
push_latest_tag=${push_latest_tag:-false}

# 加载apollo配置，会覆盖当前配置，url和appid为必输
apollo_url=${apollo_url}
apollo_appid=${apollo_appid}
apollo_namespace=${apollo_namespace}
apollo_cluster=${apollo_cluster}

# 使用远程服务器来编译和发布，不占用本地资源
remote_publish_enabled=${remote_publish_enabled:-false}
# 远程服务器地址
remote_server_address=${remote_server_address}
# 远程服务器ssh端口
remote_server_port=${remote_server_port:-22}
# 远程服务器用户
remote_server_user=${remote_server_user:-root}
# 远程服务器目录，用于存在发布的代码
remote_server_dir='${remote_server_dir:-/root/publish}'
# 邮箱地址，远程发布成功之后，会将结果发送至该邮箱
remote_publish_email=${remote_publish_email}

# 回调函数，脚本发布到镜像库结束时的回调
# on_finally='${on_finally:-[ -f config/config.js.packing ] && mv -f config/config.js.packing config/config.js}'
# 回调函数，在前端代码编译之前的回调
# on_front_build='${on_front_build:-[ -f config/config.js ] && cp config/config.js config/config.js.packing; cp -rf config/config.copy.js config/config.js; node update-router --env=\${environment}}'

EOF

	exit 0
fi

arg1=${1}
arg2=${2}
arg3=${3}
environment=${arg1}
# 当前时间
now=`date +%Y%m%d%H%M`
# 当前计算机名
computer_name="$(uname -n)"
# 当前分支
current_branch=`git branch 2> /dev/null | awk '/^\*/{print$2}'`
# 根据时间设置暂存区名称
stash_save_name=${current_branch}-`date +%Y%m%d%H%M`
# 是否暂存，1为否
stash_saved=1
# 镜像仓库地址
server=""     
# 镜像仓库用户
username=""	  
# 镜像仓库密码
password=""   
# 镜像仓库是否用http
over_http=""  
# 镜像全名
image_full_name="" 
rancher_token=""
rancher_url=""
rancher_project_id=""
rancher_namespace=""
artifact_id=""
version=""
remote_server_userdir=""
workload=""
image_name=""
image_name_is_set=""
rancher_up_status=""

function load_apollo_config() {

	[ -z "${apollo_url}" -o -z "${apollo_appid}" ] && return

	echo "加载apollo配置..."
	local apollo_cluster=${apollo_cluster:-default}
	local apollo_namespace=${apollo_namespace:-application}
	eval "`curl -s ${apollo_url}/configfiles/${apollo_appid}/${apollo_cluster}/${apollo_namespace}`"
	[ $? -ne 0 ] && echo "apollo配置加载失败！" 
	sleep 1

}

# 通过传入一个字符串，取变量名称等于该字符串的变量值
function parse_str() {

	[ -z "${1}" ] && echo -n "" || eval echo -n '$'"${1}"

}

# 去掉文件中的^M
function dos2unix() {

	[ -z "${1}" -o ! -f "${1}" ] && return
	mv -f "${1}" "${1}.tmp"
	cat "${1}.tmp" | tr -d '\r' > "${1}"
	rm -rf "${1}.tmp"

}

function get_env_by_branch() {

	if [ -n "`echo ${base_branch} | grep "${dev_branch}"`" ]; then
		environment="dev"
	elif [ -n "`echo ${base_branch} | grep "${uat_branch}"`" ]; then
		environment="uat"
	elif [ -n "`echo ${base_branch} | grep "${prod_branch}"`" ]; then
		environment="prod"
	else 
		environment="dev"
	fi

}

function parse_variables() {

	case "$arg1" in
	    "dev"|"uat"|"prod") 	
				base_branch=`parse_str "${environment}_branch"`
				;;
	    "-c")
				base_branch=${current_branch}
				if [ -n "${arg2}" ]; then
					environment="${arg2}" 
				else
					get_env_by_branch
				fi
				# 重制一下参数，便于远程发布
				arg1="-b"
				arg2="${base_branch}"
				arg3="${environment}"
	    	;;
	    "-b")
				base_branch=${arg2}
				if [ -n "${arg3}" ]; then
					environment="${arg3}"
				else
					get_env_by_branch
				fi
				;;
			"*")
				# todo show help
				echo hello
				;;
	esac	
	
	server=`parse_str "${environment}_server"`
	username=`parse_str "${environment}_username"`
	password=`parse_str "${environment}_password"`
	over_http=`parse_str "${environment}_over_http"`
	rancher_token=`parse_str "${environment}_rancher_token"`
	rancher_url=`parse_str "${environment}_rancher_url"`
	rancher_project_id=`parse_str "${environment}_rancher_project_id"`
	rancher_namespace=`parse_str "${environment}_rancher_namespace"`

	version="${tag}-${environment}-${now}"
	remote_server_userdir="${remote_server_dir}/${computer_name}"

	if [ -z "${server}" ]; then
		echo "变量${environment}_server不能为空！"
		finally 1
	fi

	# 加载远程发布环境变量
	[ -f ../remote_publish.env ] && source ../remote_publish.env

}

# 解析pom
function get_xml_value() {

	echo "`cat "$1" | grep "<$2>" | head -1 | sed -E "s/(<$2>)(.*)(<\/$2>)/\2/" | tr -d '\r' | tr -d '\t' | sed -e 's/ //g'`"

}

function get_full_image_name() {

	# 获取镜像全名，前端取前端模块名称，后端取artifactId
	if [ "${project_name}" = "${front_module_name}" ]; then
		# artifact_id="${front_module_name}"
		image_full_name=${server}${registry_extra_path}/${front_module_name}
	else
		artifact_id="$(get_xml_value ./pom.xml artifactId)"
		[ -z "${artifact_id}" ] && echo "获取artifactId失败！" && finally 1
		image_full_name=${server}${registry_extra_path}/${artifact_id}
	fi

}

function prepare() {

	echo "开始打包发布镜像到${environment:-dev}镜像库..."
	sleep 1

	if [ "${base_branch}" != "${current_branch}" ]; then

		git stash save ${stash_save_name}
		[ $? -ne 0 ] && echo "暂存代码失败！" && finally 1
		if git stash list | grep "${stash_save_name}" &> /dev/null; then 
			stash_saved=0
			echo "未提交的代码已放入暂存区${stash_save_name}..."
		fi

		echo "fetch并切换到${base_branch}分支..."
		git fetch origin ${base_branch}
		git checkout ${base_branch}

	fi

	echo "更新${base_branch}分支代码..."
	git pull origin ${base_branch} -q

	cat << EOF
======= 配置信息 =======
当前项目: ${project_name}
当前分支: ${current_branch}
打包分支: ${base_branch}
镜像库地址: ${server}
镜像库用户: ${username}
使用http: ${over_http}
镜像版本: ${version}
=======================
EOF
	if [ "${skip_verify}" != "true" ]; then
		echo -n "5秒后开始打包发布"
		for i in `seq 1 5`; do 
			printf '.' 
			sleep 1 
		done
		echo
	fi

}

function cache() {

	flag="${environment}-${project_name}"
	key="$2"
	value="$3"
	[ ! -f "${cache_file}" ] && touch "${cache_file}"
	[ -z "${key}" ] && return

	case "$1" in
	"set") 
		if [ `uname -o` = "Darwin" ]; then
			sed -i "" "/^${flag}:${key}/d" "${cache_file}"
		else
			sed -i "/^${flag}:${key}/d" "${cache_file}"
		fi
		echo "${flag}:${key}:${value}" >> "${cache_file}"
		;;
	"get")
		line="$(cat "${cache_file}" | grep "${flag}:${key}")"
		echo -n "$(echo "${line}" | cut -d':' -f3)"
		;;
	"del")
		if [ `uname -o` = "Darwin" ]; then
			sed -i "" "/^${flag}:${key}/d" "${cache_file}"
		else
			sed -i "/^${flag}:${key}/d" "${cache_file}"
		fi
		;;
	esac

}

function get_workload_info() {

	[ "${rancher_deploy}" != "true" ] && return

	if [ -n "${workload}" -a -n "${image_name}" ]; then
		image_full_name="${image_name}"
		return
	fi

	# 获取工作负载名称
	workload=$(cache get workload)
	if [ -z "${workload}" ]; then
		echo "> 默认工作负载名称：${project_name}"
		read -p "请输入Rancher中的工作负载名称：" workload
		[ -z "$workload" ] && workload=${project_name}
		cache set workload "${workload}"
		workload_is_set="1"
	fi
	# 获取镜像名称
	image_name=$(cache get image_name)
	if [ -z "${image_name}" ]; then
		echo "> 默认镜像名称：${image_full_name}"
		read -p "手动输入镜像名称[不带tag][不输入则自动拼接]：" image_name
		if [ -n "${image_name}" ]; then
			image_full_name="${image_name}"
			cache set image_name "${image_name}"
		else
			# 输入为空则让工作负载每次都自动获取
			echo "> 镜像名称设置为自动识别，以后不再提醒！"
			cache set image_name auto
		fi
		image_name_is_set="1"
	elif [ "${image_name}" != "auto" ]; then
		image_full_name="${image_name}"
	fi
	[ "${workload_is_set}" = "1" -o "${image_name_is_set}" = "1" ] && echo "> 缓存文件: ${cache_file}"
}

function upgrade_service() {

	# Rancher升级
	[ "${rancher_deploy}" != "true" ] && return

	echo "开始升级工作负载..."

	[ "${skip_verify}" = "false" ] && read -p "是否升级${environment}工作负载？[y/n]: " res || res="y"

	if [ "$res" = "y" ]; then
		! hash rancher 2> /dev/null && echo "未安装rancher-cli！" && return
		! hash kubectl 2> /dev/null && echo "未安装kubectl！" && return

		[ -z "${rancher_url}" ] && echo "rancher地址未配置！" && return

		if [ -n "${rancher_project_id}" ]; then
			rancher login "${rancher_url}" --token "${rancher_token}" --skip-verify --name "${environment}" --context "${rancher_project_id}"
		else
			echo "=== 请选择工作负载所在的项目 ==="
			rancher login "${rancher_url}" --token "${rancher_token}" --skip-verify --name "${environment}"
		fi

		cat << EOF
======= 升级信息 =======
服务端地址: ${environment}-${rancher_url}
命名空间: ${rancher_namespace}
工作负载: ${workload}
镜像名称: ${image_full_name}
镜像版本: ${version}
=======================
EOF
		local rancher_up_status=0
		rancher kubectl set image deploy "${workload}" "${workload}"="${image_full_name}":"${version}" -n "${rancher_namespace}"
		rancher_up_status=$?
		rancher kubectl rollout status deploy "${workload}" -n "${rancher_namespace}" 
		rancher_up_status=$?
		if [ "${rancher_up_status}" -ne 0 ]; then
			echo "升级工作负载异常！"
			# 升级失败则清除缓存
			[ "${workload_is_set}" = "1" ] && cache del workload
			[ "${image_name_is_set}" = "1" ] && cache del image_name
		fi
	fi

}

function front_build() {

	echo "本地编译代码..."

	hash yarn && yarn install || npm install 
	
	[ -n "${on_front_build}" ] && eval "${on_front_build}" > /dev/null

	# 先删除以前的编译文件
	# [ -n "${front_local_dirname}" -a -d "${front_local_dirname}" ] && rm -rf "${front_local_dirname}"
	[ -n "${front_build_cmd}" ] && eval "${front_build_cmd}" &> /dev/null || npm run build &> /dev/null
	[ $? -ne 0 ] && echo "代码编译失败，停止发布！" && finally 1
	# 消除颜色
	# echo -e "\033[0m"

}

function front_local_push() {

	echo "开始本地发布镜像..."
	! hash docker &> /dev/null && echo "检测到Docker程序未安装！" && finally 1
	if [ -z "${front_local_pack_dir}" -o ! -d "${front_local_pack_dir}" ]; then
		echo "请配置或创建本地打包目录！"
		finally 1
	elif [ "${front_local_pack_dir}" != "." -a "${front_local_pack_dir}" != "./" ]; then
		[ ! -d "${front_local_pack_dir}" ] && mkdir -p ${front_local_pack_dir}
		rm -rf ${front_local_pack_dir}/${front_local_dirname}
		cp -r ${front_local_dirname} ${front_local_pack_dir}
		cp -r ${front_docker_files} ${front_local_pack_dir}
	fi
	docker login ${server} -u ${username} -p ${password} &> /dev/null
	docker build -t ${image_full_name}:${version} ${front_local_pack_dir}
	docker push ${image_full_name}:${version}
	if [ "${push_latest_tag}" = "true" ]; then
		docker tag ${image_full_name}:${version} ${image_full_name}:latest
		docker push ${image_full_name}:latest
	fi
	[ $? -ne 0 ] && echo "代码打包或发布异常！" && finally 1

}

function front_online_push() {

	echo "开始远程服务器发布镜像..."
	echo "> 请注意定时清除远程服务器上用于发布镜像的临时目录！"
	# 创建临时文件夹打包镜像
	ssh ${front_server_user}@${front_server_address} \
		"mkdir -p ${front_server_dir}"
	[ $? -ne 0 ] && echo "远程打包文件夹创建失败！" && finally 1

	echo "上传docker打包文件..."
	scp -r ${front_docker_files} ${front_server_user}@${front_server_address}:${front_server_dir} > /dev/null
	echo "上传前端代码中..."
	local front_local_basename="$(basename ${front_local_dirname})"
	tar zcvf ${front_local_basename}.tar.gz -C ${front_local_dirname} . &> /dev/null
	[ $? -ne 0 ] && echo "前端代码压缩失败！" && finally 1
	# 开始上传前端文件
	scp -r ${front_local_basename}.tar.gz ${front_server_user}@${front_server_address}:${front_server_dir} > /dev/null
	[ $? -ne 0 ] && echo "代码上传失败，停止发布！" && rm -rf ${front_local_basename}.tar.gz && finally 1
	# 清理临时文件
	rm -rf ${front_local_basename}.tar.gz
	# 解压前端文件
	ssh ${front_server_user}@${front_server_address} \
		"cd ${front_server_dir} && \
		mkdir ${front_local_basename} && \
		tar zxvf ${front_local_basename}.tar.gz -C ${front_local_basename} &> /dev/null"
	# docker发布
	ssh ${front_server_user}@${front_server_address} \
		"docker login ${server} -u ${username} -p ${password} && \
		docker build -t ${image_full_name}:${version} ${front_server_dir} && \
		docker push ${image_full_name}:${version}"
	[ $? -ne 0 ] && echo "代码发布异常！" && finally 1
	if [ "${push_latest_tag}" = "true" ]; then
		ssh ${front_server_user}@${front_server_address} \
			"docker tag ${image_full_name}:${version} ${image_full_name}:latest && \
			docker push ${image_full_name}:latest"
	fi

}

function spring_boot_push() {

	echo "本地编译代码并发布镜像..."
	local build_result=0
	#jib:dockerBuild 可使用本地docker编译，不发布到远程镜像库
	# mvn dependency:resolve -U > /dev/null
	mvn compile jib:${mvn_build_method} \
		-Dbase_image="${base_image}" \
		-Dregistry_url="${server}" \
		-Dregistry_username="${username}" \
		-Dregistry_password="${password}" \
		-Dimage_tag="${version}" \
		-DsendCredentialsOverHttp="${over_http}" "${mvn_extra_param}" 
	build_result=$?
	if [ "${push_latest_tag}" = "true" ]; then
		mvn compile jib:build \
			-Dbase_image="${base_image}" \
			-Dregistry_url="${server}" \
			-Dregistry_username="${username}" \
			-Dregistry_password="${password}" \
			-Dimage_tag="latest" \
			-DsendCredentialsOverHttp="${over_http}" "${mvn_extra_param}" 
		build_result=$?
	fi
	[ "${build_result}" -ne 0 ] && echo "代码编译失败，停止发布！" && finally 1

}


function auto_build_and_push() {

	echo "开始编译并上传${project_name}镜像..."
	if [ "${project_name}" = "${front_module_name}" ]; then
		front_build
		if [ "${front_pack_method}" = "server" ]; then
			front_online_push
		elif [ "${front_pack_method}" = "local" ]; then
			front_local_push
		else 
			echo "前端打包方式配置错误！" && finally 1
		fi
	else 
		spring_boot_push
	fi

}

function remote_publish_prepare() {

	[ "${remote_publish_enabled}" != "true" ] && return

	echo "在远程服务器上发布代码到${environment}环境..."

	# [ "${skip_verify}" != "true" ] && read -p "是否自动发布到rancher？[y/n]: " res || res="y"
	# [ "${res}" = "y" ] && rancher_deploy="true" || rancher_deploy="false"

	local remote_log_file_path=${remote_server_userdir}/log/${program_file_name}_${project_name}.log

	ssh -p "${remote_server_port}" "${remote_server_user}@${remote_server_address}" "[ ! -d ${remote_server_userdir} ] && mkdir -p ${remote_server_userdir}/.project/${project_group_name/\//_}"
	scp -P "${remote_server_port}" -r "${program_file_path}" "${remote_server_user}@${remote_server_address}:${remote_server_userdir}" &> /dev/null
	scp -P "${remote_server_port}" -r "${cache_file}" "${remote_server_user}@${remote_server_address}:${remote_server_userdir}/.project/${project_group_name/\//_}" &> /dev/null
	scp -P "${remote_server_port}" -r "${project_env_file}" "${remote_server_user}@${remote_server_address}:${remote_server_userdir}/.project/${project_group_name/\//_}" &> /dev/null

	ssh -p "${remote_server_port}" "${remote_server_user}@${remote_server_address}" << EOF

#!/bin/bash

! hash git 2> /dev/null && echo "请在服务器上安装git！" && exit 1
! hash mvn 2> /dev/null && echo "请在服务器上安装maven！" && exit 1
! hash npm 2> /dev/null && echo "请在服务器上安装npm！" && exit 1

export project_env_dir=${remote_server_userdir}/.project
export TERM=xterm-256color

if grep "${project_name}" ${remote_server_userdir}/publishing.txt > /dev/null; then 
	echo "项目${project_name}正在发布中！"
	echo "> [谨慎]重置发布状态: echo -n > ${remote_server_userdir}/publishing.txt"
	exit 1
fi

echo "服务器名: \$(uname -n), 代码发布中..."

# 设置发布状态
echo "${project_name}" >> ${remote_server_userdir}/publishing.txt

[ ! -d "${remote_server_userdir}/log" ] && mkdir -p "${remote_server_userdir}/log"

cd "${remote_server_userdir}"

[ ! -d "${project_name}" ] && git clone "${git_remote_url}"
[ $? -ne 0 ] && echo "代码下载失败！" && exit 1

	# 初始化变量，用于远程发布，高优先级
	cat > "${remote_server_userdir}/remote_publish.env" << eeooff
front_pack_method=local
remote_publish_enabled=false
front_local_pack_dir=.
skip_verify=true
remote_publishing=true
remote_server_userdir=${remote_server_userdir}
project_env_dir=${remote_server_userdir}/.project
eeooff

cd "${project_name}"

../${program_file_name} ${arg1} ${arg2} ${arg3} &> ${remote_log_file_path} &

echo "> 服务器日志文件: ${remote_log_file_path}"

EOF

	exit 0
}

function send_email() {

	echo "发布完成，发送邮件通知..."

	local result_msg="成功"
	local remote_log_file_path=${remote_server_userdir}/log/${program_file_name}_${project_name}.log

	[ "${1}" -ne 0 ] && result_msg="失败"

	# dos2unix "${remote_log_file_path}" 

	mail -s "[${program_file_name}]项目${project_name}发布到${environment}${result_msg}！" "${remote_publish_email}" < "${remote_log_file_path}"

}

function finally() {

	echo "还原分支中..."
	
	if [ "${current_branch}" != "${base_branch}" ]; then
		git checkout ${current_branch} &> /dev/null
		if [ "${stash_saved}" -eq 0 ]; then
			echo "恢复暂存区${stash_save_name}代码..."
			stash_save_code=$(git stash list | grep "${stash_save_name}" | cut -d':' -f1)
			if [ -z "${stash_save_code}" ]; then
				echo "暂存区代码未找到！"
			else
				git stash apply "${stash_save_code}"
			fi
		fi
	fi

	if [ "${remote_publishing}" = "true" ]; then
		sed -i "/${project_name}/d" ../publishing.txt
		send_email "${1}"
	fi

	[ -n "${on_finally}" ] && eval "${on_finally}"

	exit

}

function main_process() {

	load_apollo_config

	parse_variables

	get_full_image_name

	get_workload_info

	remote_publish_prepare

	prepare

	auto_build_and_push

	upgrade_service

	finally 0

}

main_process

